compressionLevel: mixed

enableGlobalCache: true

httpTimeout: 300000

nodeLinker: node-modules
npmScopes:
  anpeni:
    npmAuthToken: "${GH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
