name: 'Formulario de Bug'
description: 'Archivo para crear un formulario personalizado de bug'
title: ':bug: []: '
labels: ['bug']
projects: ['DDC-NEORIS/19']
body:
  - type: markdown
    attributes:
      value: |
        :pencil: Proporcione un resumen general del problema en el título arriba.
  - type: textarea
    id: description
    attributes:
      label: '**📝 Descripción**'
      description: 'Explique en detalle el problema que está experimentando.'
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: '**🔬 Pasos para Reproducir**'
      description: 'Proporcione los pasos necesarios para reproducir este problema.'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: '**✅ Comportamiento Esperado**'
      description: 'Describa lo que esperaba que sucediera cuando siguió los pasos anteriores.'
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: '**❌ Comportamiento Actual**'
      description: 'Describa lo que realmente sucedió cuando siguió los pasos anteriores.'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: '📸 Capturas de Pantalla'
      description: 'Si es aplicable, añada capturas de pantalla para ayudar a explicar su problema.'
    validations:
      required: false
  - type: textarea
    id: system-information
    attributes:
      label: '🖥️ Información del Sistema'
      description: 'Proporcione detalles sobre su entorno, como la versión del sistema operativo, la versión del navegador, etc.'
    validations:
      required: false
