name: 'Formulario de Feature'
description: 'Archivo para crear un formulario personalizado de feature'
title: ':rocket: []: '
labels: ['enhancement']
projects: ['DDC-NEORIS/19']
body:
  - type: markdown
    attributes:
      value: |
        :pencil: Proporcione un resumen general del problema en el título arriba.
  - type: textarea
    id: description
    attributes:
      label: '**📝 Descripción**'
      description: 'Explique en detalle el propósito de esta investigación.'
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: '**✅ Criterios de Aceptación**'
      description: 'Indique los resultados esperados de esta investigación.'
    validations:
      required: true
  - type: textarea
    id: integration-plan
    attributes:
      label: 'Plan de Integración'
      description: 'Si es aplicable, proponga un plan para la integración de la herramienta en el proyecto.'
    validations:
      required: false
