apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-sql-server
  title: '@backstage/plugin-sql-server'
  description: A Backstage backend plugin that integrates towards sql server
spec:
  lifecycle: experimental
  type: backstage-backend-plugin
  owner: maintainers
