name: Publish to Github Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      NODE_OPTIONS: ${{ matrix.node-version == '20.x' && '--max-old-space-size=8192 --no-node-snapshot' || '--max-old-space-size=8192' }}

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Yarn
        run: npm install -g yarn

      - name: Check Yarn version
        run: yarn --version

      - name: Configure .yarnrc.yml
        run: |
          cat > .yarnrc.yml <<EOF
          enableGlobalCache: true
          httpTimeout: 300000
          nodeLinker: node-modules
          npmRegistryServer: 'https://registry.npmjs.org/'
          yarnPath: .yarn/releases/yarn-3.8.1.cjs
          npmRegistries:
            "https://npm.pkg.github.com":
              npmAuthToken: "${{ secrets.GITHUB_TOKEN }}"
          npmScopes:
            ddc-neoris:
              npmRegistryServer: "https://npm.pkg.github.com"
          EOF
          cat .yarnrc.yml

      - name: Install dependencies
        run: yarn install

      - name: Generate TypeScript declaration files
        run: yarn tsc

      - name: build
        run: yarn backstage-cli repo build --all

      - name: Publish to GitHub Packages
        run: yarn workspaces foreach --all --no-private -v npm publish --access restricted --tolerate-republish --tag latest
