name: Publish to Github Packages

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Yarn 4
        run: yarn set version 4.2.2

      - name: Iterate over directories and execute commands
        run: |
          for dir in ./workspace/*; do
            if [ -d "$dir" ]; then
              echo "Working in $dir"
              cd $dir
              
              # Create .yarnrc.yml
              echo 'npmRegistries:' > .yarnrc.yml 
              echo ' "https://npm.pkg.github.com":' >> .yarnrc.yml 
              echo '    npmAuthToken: "${{ secrets.GITHUB_TOKEN }}"' >> .yarnrc.yml 
              echo 'npmScopes:' >> .yarnrc.yml 
              echo '  anpeni:' >> .yarnrc.yml 
              echo '    npmRegistryServer: "https://npm.pkg.github.com"' >> .yarnrc.yml
              cat .yarnrc.yml

              # Install dependencies
              yarn install 

              # Compile TypeScript
              yarn tsc:full

              # Build all packages
              yarn build:all

              # Publish to GitHub Packages
              echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
              yarn config set npmRegistryServer "https://npm.pkg.github.com"
              yarn workspaces foreach --all --no-private -v npm publish --access restricted --tolerate-republish --tag latest

              cd -  # go back to the previous directory
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
