name: Publish to Github Packages
 
on:
  push:
    branches:
      - main
 
jobs:
  publish:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: ['18.18.2']
 
    env:
      NODE_OPTIONS: ${{ matrix.node-version == '18.18.2' && '--max-old-space-size=8192 --no-node-snapshot' || '--max-old-space-size=8192' }}
 
    steps:
      - uses: actions/checkout@v4.1.6
 
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
 
      - name: Install Yarn
        run: npm install -g yarn
 
      - name: Install TypeScript
        run: npm install -g typescript@5.3.2
 
      - name: Print Node.js, Yarn and TypeScript versions
        run: |
          echo "Node.js version:"
          node --version
          echo "Yarn version:"
          yarn --version
          echo "TypeScript version:"
          tsc --version
 
      - name: Configure .yarnrc.yml
        run: |
          echo "enableGlobalCache: true" > .yarnrc.yml
          echo "httpTimeout: 300000" >> .yarnrc.yml
          echo "nodeLinker: node-modules" >> .yarnrc.yml
          echo "npmRegistryServer: 'https://registry.npmjs.org/'" >> .yarnrc.yml
          echo "plugins:" >> .yarnrc.yml
          echo "  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs" >> .yarnrc.yml
          echo "    spec: '@yarnpkg/plugin-workspace-tools'" >> .yarnrc.yml
          echo "yarnPath: .yarn/releases/yarn-4.2.2.cjs" >> .yarnrc.yml
          echo "npmRegistries:" >> .yarnrc.yml
          echo "  \"https://npm.pkg.github.com\":" >> .yarnrc.yml
          echo "    npmAuthToken: \"${{ secrets.GH_TOKEN }}\"" >> .yarnrc.yml
          echo "npmScopes:" >> .yarnrc.yml
          echo "  anpeni:" >> .yarnrc.yml
          echo "    npmRegistryServer: \"https://npm.pkg.github.com\"" >> .yarnrc.yml
          cat .yarnrc.yml
 
      - name: Install dependencies
        run: yarn install
 
      - name: Generate TypeScript declaration files
        run: yarn tsc
 
      - name: build
        run: yarn backstage-cli repo build --all
 
      - name: Publish to GitHub Packages
        run: yarn workspaces foreach --all --no-private -v npm publish --access restricted --tolerate-republish --tag latest